version: '3'

services:
  # Node.js application
  web:
    image: profanor/ecommerce
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: "production"  # Set the environment to production
    volumes:
      - ./app:/app  # Mount a volume to share application code between host and container

  # SQLite database
  db:
    image: sqlite:latest
    volumes:
      - ./data:/data  # Mount a volume to persist the SQLite database file